### ISSUE TITLE
Support async mapFn

### ISSUE THREAD

**Issue by Pytal** [syntax-tree/unist-util-map#2]
### Support async mapFn

For asynchronous operations it'd be great if we could pass an async function as the `mapFn` e.g.

```js
map(tree, async (node) => {
  await asyncFn()
})
```

### Problem

Can't perform async operations when mapping over nodes.

### Expected behavior

Should be able to use `await` inside an async `mapFn`

### Alternatives

Visit nodes and perform async operations in the [transformer](https://github.com/unifiedjs/unified#function-transformernode-file-next).

**Comment by wooorm** [comment]
For adding it to this project, if it were accepted, it should be supported in the other similar projects to: https://github.com/syntax-tree/unist-util-map#related.

This is definitely something that you could build yourself btw!

A tree can contain millions of nodes (e.g., for a book). `.then`ing a million promises is going to be very slow.

Can you instead solve it [like so](https://spectrum.chat/unified/syntax-tree/is-there-any-way-to-execute-async-work-when-visiting-a-node-in-unist-util-visit~28177826-628e-44e3-ac3e-0ffb53c195c6?m=MTU4MTM2ODQ3ODgwMQ==)?

Or, perhaps, could you tell me more about what you want to achieve?

**Comment by wooorm** [comment]
Closing as it’s unclear how this would work and could be done in userland
