### ISSUE TITLE
Cannot change `children` field

### ISSUE THREAD

**Issue by stegano** [syntax-tree/unist-util-map#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I replaced the `children` field but the returned object did not reflect the change.

### Solution

I think this library should provide a means to change the `children` filed to a new value(new reference).

### Alternatives

.

**Comment by wooorm** [comment]
This behavior is documented: https://github.com/syntax-tree/unist-util-map#maptree-mapfunction.

Why do you want this?

I think you can solve this by inverting your thinking: you are given a `node` *and* a parent. Change `node` based on what `parent` it has.

**Comment by stegano** [comment]
Hi @wooorm,

Thanks for your reply.

I had a problem when trying to change the number of child nodes in my case.

Like you said, it's possible to handle it somehow by referring to the parent node, but I don't think this approach is optimal. The map function should return a transformed object, and referring to and modifying the parent node could potentially cause side effects.

Please let me know if I'm misunderstanding something.

**Comment by wooorm** [comment]
Why are you using this project, when you want to change the number of child nodes?
Why not `unist-util-visit`, which provides much more power?
Or `unist-util-filter` / `unist-util-remove`?

Perhaps you can share more about your use case?

**Comment by stegano** [comment]
In my project, I am using `unist` to create or modify a Virtual DOM tree.

Since the DOM tree has a complex nested structure, I concluded that it is not suitable to handle each node using filter or remove (due to processing speed and complexity), and I believe that the map utility is the most appropriate approach.

**Comment by wooorm** [comment]
> Virtual DOM tree

What virtual DOM? Why not use [hast](https://github.com/syntax-tree/hast)?

>  I believe that the map utility is the most appropriate approach.

This project is slow. See the readme: https://github.com/syntax-tree/unist-util-map#when-should-i-use-this.
Changing the tree, instead of creating new objects for every object, is much much faster. Hence why I strongly recommend `unist-util-visit`

**Comment by stegano** [comment]
Thank you for letting me know about hast. I will give it a try.

Isn't `unist-util-visit` util intended for traversing specific nodes? If it's possible to handle it with map, wouldn't it be better to use a map without side effects?

**Comment by stegano** [comment]
I will try it using the methods you have suggested

I realized that my problem was trying to solve it using the approach I had been using before, as I am not yet familiar with the syntax-tree library.

Thank you for informing me 😀

**Comment by wooorm** [comment]
> If it's possible to handle it with map, wouldn't it be better to use a map without side effects?

No, side effects are faster than copying each node.
Only when (almost) all nodes need to change, such as when turning mdast (markdown) into hast (HTML) or so, it makes sense to change each object (without side effects).

That is because trees can be giant. And often, you only want to change a couple things.

> Isn't `unist-util-visit` util intended for traversing specific nodes?

It can basically do anything, it’s very powerful! See also:
- https://unifiedjs.com/learn/recipe/tree-traversal/
- https://unifiedjs.com/learn/recipe/find-node/
- https://unifiedjs.com/learn/recipe/remove-node/

However, I still don’t really know what you practically wan’t to do (“change the number of child nodes in my case.”)? If you share that, I can provide a more practical example.

**Comment by stegano** [comment]
> > If it's possible to handle it with map, wouldn't it be better to use a map without side effects?
> 
> No, side effects are faster than copying each node. Only when (almost) all nodes need to change, such as when turning mdast (markdown) into hast (HTML) or so, it makes sense to change each object (without side effects).
> 
> That is because trees can be giant. And often, you only want to change a couple things.
> 
> > Isn't `unist-util-visit` util intended for traversing specific nodes?
> 
> It can basically do anything, it’s very powerful! See also:
> 
> * https://unifiedjs.com/learn/recipe/tree-traversal/
> * https://unifiedjs.com/learn/recipe/find-node/
> * https://unifiedjs.com/learn/recipe/remove-node/
> 
> However, I still don’t really know what you practically wan’t to do (“change the number of child nodes in my case.”)? If you share that, I can provide a more practical example.

Thank you for your response. 

I was just trying to change the number of child nodes using the `unist-util-map` library.

For example, if there are nodes a -> b,c and I want to remove all of the children of node a, the ideal way that I had in mind was as follows:
```ts
map(tree, (currentNode) => { 
  currentNode.children = [];
  return currentNode;
});
```

However, this library cannot handle it that way and requires modification through the parent node's reference. 
Modifying the parent node during the loop makes it difficult to predict the modified values of the node while the loop is executed (e.g. referencing a deleted node may cause errors).

Of course, in some cases, it may be possible to use the library you suggested. 
However, I was just talking about the unist-util-map library.

Therefore, I would like to see a feature that can replace the children object, as in the #9 PR.

Thank you.

**Comment by wooorm** [comment]
> I would like to see a feature that can replace the children object

I think such a feature is confusing.
Mapping works by calling a given function `f` with all old values (`x`) to receive all new values (`y`).
Mapping on an array does one thing, other than iterating: `y = f(x)`.
Other than walking, I think this utility should do the same.
Mapping doesn’t “filter” or “reduce”.

As we have a tree structure, we need to look for `children` for values.
But on a new value, it is nonsensical that there are old values in children.
If you return children on a new node, I think it makes more sense that they are expected to be new, mapped, values.
Instead of old, filtered, values.
But as this is confusing, I think ignoring `children` on new nodes makes more sense?

Perhaps @remcohaszing or @ChristianMurphy have opinions on this.

---

> ```js
> map(tree, (currentNode) => { 
>   currentNode.children = [];
>   return currentNode;
> });
> ```

I suggest:

```js
import {visit, SKIP} from 'unist-util-visit'

const tree = {type: 'someNode'}
const a = { type: 'someOtherNode' }

visit(tree, (node) => { 
  if (node === a) {
    node.children = []
    return SKIP
  }
})
```

Your example remains theoretical, perhaps you can provide an actual, practical, example.

**Comment by stegano** [comment]
> > I would like to see a feature that can replace the children object
> 
> I think such a feature is confusing. Mapping works by calling a given function `f` with all old values (`x`) to receive all new values (`y`). Mapping on an array does one thing, other than iterating: `y = f(x)`. Other than walking, I think this utility should do the same. Mapping doesn’t “filter” or “reduce”.
> 
> As we have a tree structure, we need to look for `children` for values. But on a new value, it is nonsensical that there are old values in children. If you return children on a new node, I think it makes more sense that they are expected to be new, mapped, values. Instead of old, filtered, values. But as this is confusing, I think ignoring `children` on new nodes makes more sense?
> 
> Perhaps @remcohaszing or @ChristianMurphy have opinions on this.
> 
> > ```js
> > map(tree, (currentNode) => { 
> >   currentNode.children = [];
> >   return currentNode;
> > });
> > ```
> 
> I suggest:
> 
> ```js
> import {visit, SKIP} from 'unist-util-visit'
> 
> const tree = {type: 'someNode'}
> const a = { type: 'someOtherNode' }
> 
> visit(tree, (node) => { 
>   if (node === a) {
>     node.children = []
>     return SKIP
>   }
> })
> ```
> 
> Your example remains theoretical, perhaps you can provide an actual, practical, example.

Thank you for your answer.

The reason why I suggested `replaceChildren`(#8) was just because I expected this library to behave similar to `Array.map` behavior.

If using the `unist-util-visit` library as you suggested would be more efficient for handling trees, I think it would be a good idea to use `unist-util-visit`.

Thank you. :)

**Comment by stegano** [comment]
`hast` seems to be the library I was searching for. Thank you for creating and informing us about this excellent library!

**Comment by wooorm** [comment]
Cool cool!

I still feel weird about this, summarising my earlier comment and adding some more:

Mapping works by calling a given function `f` with an old value (`x`) to receive a new value (`y`).
Mapping on an array does one thing, other than iterating: `y = f(x)`.

Of course, compared to `Array#map`, we are *recursively* iterating, so we must get next arrays to iterate from some value, and then we’ll call `f` on those old values to get new values too.

The only places where *old* values exist are on *old* nodes. I think it‘s weird to expect *old* values to exist on the *new* value.

So, I’m leaning against this, and I think it’s fine to close this as you found a viable alternative. I’m open to more arguments though, if readers have them.

Thanks!
